name: TESTS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.4'
          - '8.3'
          - '8.2'

    name: Tests (PHP ${{ matrix.php }} - ${{ matrix.deps }})

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install dependencies
        run: composer update

      - name: Tests code
        run: composer tests

      - name: Tests coverage
        run: composer tests-coverage

      - name: Tests mutation
        run: composer tests-mutation
